// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEBAPIPROJ.Models;

namespace WEBAPIPROJ.Migrations
{
    [DbContext(typeof(UtakmicaContext))]
    [Migration("20210821172234_v4")]
    partial class v4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("WEBAPIPROJ.Models.Lokacija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int>("Domaci")
                        .HasColumnType("int")
                        .HasColumnName("Domaci");

                    b.Property<int>("Gosti")
                        .HasColumnType("int")
                        .HasColumnName("Gosti");

                    b.Property<string>("Stat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Stat");

                    b.Property<int>("UtakmicaID")
                        .HasColumnType("int");

                    b.Property<int>("x")
                        .HasColumnType("int")
                        .HasColumnName("x");

                    b.HasKey("ID");

                    b.HasIndex("UtakmicaID");

                    b.ToTable("Lokacija");
                });

            modelBuilder.Entity("WEBAPIPROJ.Models.Sluzbenalica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<string>("Glavni")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Glavni");

                    b.Property<string>("Pomocnik1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Pomocnik1");

                    b.Property<string>("Pomocnik2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Pomocnik2");

                    b.Property<int>("UtakmicaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UtakmicaID");

                    b.ToTable("SLuzbena lica");
                });

            modelBuilder.Entity("WEBAPIPROJ.Models.Sudija", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<int?>("UtakmicaID")
                        .HasColumnType("int");

                    b.Property<string>("gp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gp");

                    b.Property<string>("sudija")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sudija");

                    b.HasKey("id");

                    b.HasIndex("UtakmicaID");

                    b.ToTable("Sudije");
                });

            modelBuilder.Entity("WEBAPIPROJ.Models.Utakmica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<string>("Domacin")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Domacin");

                    b.Property<string>("Gost")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Gost");

                    b.HasKey("ID");

                    b.ToTable("Utakmica");
                });

            modelBuilder.Entity("WEBAPIPROJ.Models.Lokacija", b =>
                {
                    b.HasOne("WEBAPIPROJ.Models.Utakmica", "Utakmica")
                        .WithMany("Lokacije")
                        .HasForeignKey("UtakmicaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utakmica");
                });

            modelBuilder.Entity("WEBAPIPROJ.Models.Sluzbenalica", b =>
                {
                    b.HasOne("WEBAPIPROJ.Models.Utakmica", "Utakmica")
                        .WithMany("Sluzbenalica")
                        .HasForeignKey("UtakmicaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utakmica");
                });

            modelBuilder.Entity("WEBAPIPROJ.Models.Sudija", b =>
                {
                    b.HasOne("WEBAPIPROJ.Models.Utakmica", "Utakmica")
                        .WithMany("Sudije")
                        .HasForeignKey("UtakmicaID");

                    b.Navigation("Utakmica");
                });

            modelBuilder.Entity("WEBAPIPROJ.Models.Utakmica", b =>
                {
                    b.Navigation("Lokacije");

                    b.Navigation("Sluzbenalica");

                    b.Navigation("Sudije");
                });
#pragma warning restore 612, 618
        }
    }
}
